
version: 2



models:
    - name: production_user
      description: "Copying the production_user materialized view from the analytics db"
      columns:
          - name: company_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: origin
            description: "The origin of the user account"
            tests:
              - is_valid_user_origin
          
sources:
  - name: RAW_PLATFORM
    database: RAW  # Tell dbt to look for the source in the "raw" database
    schema: PLATFORM_REPLICA_PUBLIC # You wouldn't put your source data in public, would you?
    tables:
      - name: USERS
      - name: SUBCONTRACTOR_PROFILES
      - name: OPERATORS
      - name: VENDORS
      - name: SUBCONTRACTOR_PAYMENT_SCHEDULES
      - name: LABOR_ACCOUNTING_RATES
      - name: LABOR_ACCOUNTING_RATE_SETS
      - name: SUBCONTRACTOR_JOBS